services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true
        bind:
            string $devServerOrigin: '%vite.dev_server%'
            string $cdnUrl: '%vite.app_cdn%'
            string $vitePublicBasePath: '%vite.public_base_path%'

    Vite\:
        resource: '../../'
        exclude: '../../Dto'
